name: "Newton's Old Pueblo Jerky"
favicon: null
layout_spectrum: 0.6182795
typography_spectrum: 0.2789725
title: The Best Jerky from Jerky Man Mike
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#e3b085'
    - '#6f362b'
    - '#14110c'
    - '#98a089'
  brandStrength: 0.3125
  lightness: 0.8226517
  saturation: 0.75
  rhythmicContrast: 0.2295808
purpose: []
